#!/usr/bin/env bash
# Load functions and variables
. /usr/bin/common
# Display ssh logo
ssh_logo

cat << "EOF"
Connect your Device to this computer or plug in an Ethernet cable (If Ethernet dosen't work, go into Termianl and run setup-interfaces)

The keyboard layout is in American Qwerty.

EOF
prompt 'User: ' user
prompt 'Port: ' port
prompt 'IP: ' ip
prompt 'Password: ' password

clear

blue_echo 'SSHing into your Device...'
ssh -o "ProxyCommand=inetcat $port" -o "UserKnownHostsFile=/dev/null"  '$user:$password@$ip' || \
    failed_echo 'Failed to SSH into your Device.'
enter_to_quit
