name: Build MTR

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        arch: [ amd64, i686 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: version
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV

      - name: Build
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          sudo ./build-auto-amd64.sh
      - name: Draft release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: work/*.iso
